project_name: certstream-server-go

before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/certstream-server-go/
    ldflags: -s -w -X github.com/spudstr/certstream-server-go/internal/config.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: 386
checksum:
  name_template: '{{.ProjectName}}_{{.Version}}_checksums.txt'
changelog:
  skip: true

dockers:
  - image_templates:
      - 'spudstr/{{.ProjectName}}:{{.Tag}}-amd64'
      - '{{ if not .Prerelease }}spudstr/{{.ProjectName}}:{{.Tag}}{{ end }}'
      - 'ghcr.io/spudstr/{{.ProjectName}}:{{.Tag}}-amd64'
      - '{{ if not .Prerelease }}ghcr.io/spudstr/{{.ProjectName}}:latest-amd64{{ end }}'
    goarch: amd64
    use: buildx
    extra_files:
      - config.sample.yaml
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description=Certstream server written in Go"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.source=https://github.com/spudstr/certstream-server-go"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"

  - image_templates:
      - 'spudstr/{{.ProjectName}}:{{.Tag}}-arm64'
      - '{{ if not .Prerelease }}spudstr/{{.ProjectName}}:latest-arm64{{ end }}'
      - 'ghcr.io/spudstr/{{.ProjectName}}:{{.Tag}}-arm64'
      - '{{ if not .Prerelease }}ghcr.io/spudstr/{{.ProjectName}}:latest-arm64{{ end }}'
    goarch: arm64
    use: buildx
    extra_files:
      - config.sample.yaml
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description=Certstream server written in Go"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.source=https://github.com/spudstr/certstream-server-go"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: 'spudstr/{{.ProjectName}}:{{.Tag}}'
    image_templates:
      - 'spudstr/{{.ProjectName}}:{{.Tag}}-amd64'
      - 'spudstr/{{.ProjectName}}:{{.Tag}}-arm64'

  - name_template: 'ghcr.io/spudstr/{{.ProjectName}}:{{.Tag}}'
    image_templates:
      - 'ghcr.io/spudstr/{{.ProjectName}}:{{.Tag}}-amd64'
      - 'ghcr.io/spudstr/{{.ProjectName}}:{{.Tag}}-arm64'

  - name_template: '{{ if not .Prerelease }}spudstr/{{.ProjectName}}:latest{{ end }}'
    image_templates:
      - 'spudstr/{{.ProjectName}}:{{.Tag}}-amd64'
      - 'spudstr/{{.ProjectName}}:{{.Tag}}-arm64'

  - name_template: '{{ if not .Prerelease }}ghcr.io/spudstr/{{.ProjectName}}:latest{{ end }}'
    image_templates:
      - 'ghcr.io/spudstr/{{.ProjectName}}:{{.Tag}}-amd64'
      - 'ghcr.io/spudstr/{{.ProjectName}}:{{.Tag}}-arm64'

archives:
  - format: binary
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version}}_
      {{- if eq .Os "darwin" }}macOS{{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}
