webserver:
  listen_addr: "0.0.0.0"
  listen_port: 8080
  full_url: "/full-stream"
  lite_url: "/"
  domains_only_url: "/domains-only"
  cert_path: ""
  cert_key_path: ""
  whitelist: 
    - "0.0.0.0/0"

prometheus:
  enabled: true
  listen_addr: "0.0.0.0"
  listen_port: 8080
  metrics_url: "/metrics"
  expose_system_metrics: true
  real_ip: true
  whitelist:
    - "0.0.0.0/0"

