name: build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Release build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Setup QEMU # Used for cross-compiling with goreleaser / docker
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx # Used for cross-compiling with goreleaser / docker
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --config .github/goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
